# Generated by Django 3.2.5 on 2021-08-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='value',
        ),
        migrations.AddField(
            model_name='measurement',
            name='air_quality',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='gas_resistance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
