# Generated by Django 3.2.7 on 2021-09-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210802_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
    ]
